### ISSUE TITLE
Unable to get rrdcached working with example compose file

### ISSUE THREAD

**Issue by 33Fraise33** [librenms/docker#40]
### Behaviour
When running the docker compose file with own variables the created directories are not being created with the correct UID & GID. mariadb is taking 999:999 and the other ones are just using 0:0 even though I overruled them with 1000:1000.

rrdcached is then complaining it cannot write to that directory. So I'm unsure what is going wrong. I already tried to create the mysql user and group id's and assigning those in the .env but without solving the issue.

#### Steps to reproduce this issue

1. Use the files from down below to start docker-compose. See the result in the logs. 
2.
3.

#### Expected behaviour

rrdcached should be working

#### Actual behaviour

rrdcached is complainging about file permissions even though everything is set correctly. 

### Configuration

* Docker version (type `docker --version`) : `Docker version 19.03.4, build 9013bf583a`
* Docker compose version if applicable (type `docker-compose --version`) : `docker-compose version 1.24.1, build 4667896b`
* Platform (Debian 9, Ubuntu 18.04, ...) : `Debian 9.11`
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

### Docker info

```
$Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 7
  Paused: 0
  Stopped: 1
 Images: 6
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.0-9-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.38GiB
 Name: thanos
 ID: MQQ4:SQAG:6T2K:NNJC:GX5K:J7HT:53UI:25F3:E3B7:2RHY:23YH:K6JU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Logs

```
librenms_syslog | Setting timezone to Europe/Paris...
librenms_syslog | Checking if librenms UID / GID has changed...
librenms_syslog | Setting PHP-FPM configuration...
librenms_syslog | Setting PHP INI configuration...
librenms_syslog | Setting OpCache configuration...
librenms_syslog | Setting Nginx configuration...
librenms_syslog | Updating SNMP community...
librenms_syslog | Initializing LibreNMS files / folders...
librenms_syslog | Setting LibreNMS configuration...
librenms_syslog | Fixing permissions...
librenms_syslog | Checking additional Monitoring plugins...
librenms_syslog | >>
librenms_syslog | >> Sidecar syslog-ng container detected
librenms_syslog | >>
librenms_syslog | 2019-10-20 17:27:38,448 INFO Included extra file "/etc/supervisord/syslog-ng.conf" during parsing
librenms_syslog | 2019-10-20 17:27:38,448 INFO Set uid to user 0 succeeded
librenms_syslog | 2019-10-20 17:27:38,454 INFO RPC interface 'supervisor' initialized
librenms_syslog | 2019-10-20 17:27:38,454 CRIT Server 'unix_http_server' running without any HTTP authentication checking
librenms_syslog | 2019-10-20 17:27:38,454 INFO supervisord started with pid 1
librenms_syslog | 2019-10-20 17:27:39,456 INFO spawned: 'syslog-ng' with pid 44
librenms_syslog | [2019-10-20T17:27:39.460875] WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.19 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file.;
librenms_syslog | [2019-10-20T17:27:39.462539] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
librenms_syslog | 2019-10-20 17:27:40,463 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
librenms     | Setting timezone to Europe/Paris...
librenms     | Checking if librenms UID / GID has changed...
librenms     | Setting PHP-FPM configuration...
librenms     | Setting PHP INI configuration...
librenms     | Setting OpCache configuration...
librenms     | Setting Nginx configuration...
librenms     | Updating SNMP community...
librenms     | Initializing LibreNMS files / folders...
librenms     | Setting LibreNMS configuration...
librenms     | Fixing permissions...
librenms     | Checking additional Monitoring plugins...
librenms     | Waiting 30s for database to be ready...
librenms     | ERROR: Failed to connect to database on db
librenms     | Setting timezone to Europe/Paris...
librenms     | Checking if librenms UID / GID has changed...
librenms     | Setting PHP-FPM configuration...
librenms     | Setting PHP INI configuration...
librenms     | Setting OpCache configuration...
librenms     | Setting Nginx configuration...
librenms     | Updating SNMP community...
librenms     | Initializing LibreNMS files / folders...
librenms     | Setting LibreNMS configuration...
librenms     | Fixing permissions...
librenms     | Checking additional Monitoring plugins...
librenms     | rm: cannot remove '/etc/supervisord/cron.conf': No such file or directory
librenms     | rm: cannot remove '/etc/supervisord/syslog-ng.conf': No such file or directory
librenms     | Waiting 30s for database to be ready...
librenms     | ERROR: Failed to connect to database on db
librenms     | Setting timezone to Europe/Paris...
librenms     | Checking if librenms UID / GID has changed...
librenms     | Setting PHP-FPM configuration...
librenms     | Setting PHP INI configuration...
librenms     | Setting OpCache configuration...
librenms     | Setting Nginx configuration...
librenms     | Updating SNMP community...
librenms     | Initializing LibreNMS files / folders...
librenms     | Setting LibreNMS configuration...
librenms     | Fixing permissions...
librenms     | Checking additional Monitoring plugins...
librenms     | rm: cannot remove '/etc/supervisord/cron.conf': No such file or directory
librenms     | rm: cannot remove '/etc/supervisord/syslog-ng.conf': No such file or directory
librenms     | Waiting 30s for database to be ready...
librenms     | Database ready!
librenms     | Updating database schema...
librenms     | Failed to acquire lock schema
librenms     | Creating admin user...
librenms     | 
librenms     | In StreamHandler.php line 107:
librenms     |                                                                                
librenms     |   The stream or file "/opt/librenms/logs/librenms.log" could not be opened: f  
librenms     |   ailed to open stream: Permission denied                                      
librenms     |                                                                                
librenms     | 
librenms     | 2019-10-20 17:28:45,166 INFO Included extra file "/etc/supervisord/nginx.conf" during parsing
librenms     | 2019-10-20 17:28:45,166 INFO Included extra file "/etc/supervisord/php.conf" during parsing
librenms     | 2019-10-20 17:28:45,166 INFO Included extra file "/etc/supervisord/snmpd.conf" during parsing
librenms     | 2019-10-20 17:28:45,166 INFO Set uid to user 0 succeeded
librenms     | 2019-10-20 17:28:45,172 INFO RPC interface 'supervisor' initialized
librenms     | 2019-10-20 17:28:45,172 CRIT Server 'unix_http_server' running without any HTTP authentication checking
librenms     | 2019-10-20 17:28:45,172 INFO supervisord started with pid 1
librenms     | 2019-10-20 17:28:46,175 INFO spawned: 'nginx' with pid 70
librenms     | 2019-10-20 17:28:46,178 INFO spawned: 'php' with pid 71
librenms     | 2019-10-20 17:28:46,179 INFO spawned: 'snmpd' with pid 72
librenms     | 2019/10/20 17:28:46 [notice] 70#70: using the "epoll" event method
librenms     | 2019/10/20 17:28:46 [notice] 70#70: nginx/1.16.1
librenms     | 2019/10/20 17:28:46 [notice] 70#70: OS: Linux 4.9.0-9-amd64
librenms     | 2019/10/20 17:28:46 [notice] 70#70: getrlimit(RLIMIT_NOFILE): 1048576:1048576
librenms     | 2019/10/20 17:28:46 [notice] 70#70: start worker processes
librenms     | 2019/10/20 17:28:46 [notice] 70#70: start worker process 73
librenms     | 2019/10/20 17:28:46 [notice] 70#70: start worker process 74
librenms     | 2019/10/20 17:28:46 [notice] 70#70: start worker process 75
librenms     | 2019/10/20 17:28:46 [notice] 70#70: start worker process 76
librenms     | 2019/10/20 17:28:46 [notice] 70#70: start worker process 77
librenms     | 2019/10/20 17:28:46 [notice] 70#70: start worker process 78
librenms     | 2019/10/20 17:28:46 [notice] 70#70: start worker process 79
librenms     | 2019/10/20 17:28:46 [notice] 70#70: start worker process 83
librenms     | [20-Oct-2019 17:28:46] NOTICE: fpm is running, pid 71
librenms     | [20-Oct-2019 17:28:46] NOTICE: ready to handle connections
librenms     | 2019-10-20 17:28:47,209 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
librenms     | 2019-10-20 17:28:47,209 INFO success: php entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
librenms     | 2019-10-20 17:28:47,209 INFO success: snmpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
db_1         | Initializing database
db_1         | 
db_1         | 
db_1         | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
db_1         | To do so, start the server, then issue the following commands:
db_1         | 
db_1         | '/usr/bin/mysqladmin' -u root password 'new-password'
db_1         | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
db_1         | 
db_1         | Alternatively you can run:
db_1         | '/usr/bin/mysql_secure_installation'
db_1         | 
db_1         | which will also give you the option of removing the test
db_1         | databases and anonymous user created by default.  This is
db_1         | strongly recommended for production servers.
db_1         | 
db_1         | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
db_1         | MySQL manual for more instructions.
db_1         | 
db_1         | Please report any problems at http://mariadb.org/jira
db_1         | 
db_1         | The latest information about MariaDB is available at http://mariadb.org/.
db_1         | You can find additional information about the MySQL part at:
db_1         | http://dev.mysql.com
db_1         | Consider joining MariaDB's strong and vibrant community:
db_1         | https://mariadb.org/get-involved/
db_1         | 
db_1         | Database initialized
db_1         | MySQL init process in progress...
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] mysqld (mysqld 10.2.27-MariaDB-1:10.2.27+maria~bionic) starting as process 108 ...
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: Uses event mutexes
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: Using Linux native AIO
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: Number of pools: 1
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: Using SSE2 crc32 instructions
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: Completed initialization of buffer pool
db_1         | 2019-10-20 17:27:36 140307321644800 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: Highest supported file format is Barracuda.
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: 128 out of 128 rollback segments are active.
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] InnoDB: 5.7.27 started; log sequence number 1619987
db_1         | 2019-10-20 17:27:36 140307152746240 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] Plugin 'FEEDBACK' is disabled.
db_1         | 2019-10-20 17:27:36 140308044023104 [Warning] 'user' entry 'root@28a036cf7b3c' ignored in --skip-name-resolve mode.
db_1         | 2019-10-20 17:27:36 140308044023104 [Warning] 'proxies_priv' entry '@% root@28a036cf7b3c' ignored in --skip-name-resolve mode.
db_1         | 2019-10-20 17:27:36 140307152746240 [Note] InnoDB: Buffer pool(s) load completed at 191020 17:27:36
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] Reading of all Master_info entries succeeded
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] Added new Master_info '' to hash table
db_1         | 2019-10-20 17:27:36 140308044023104 [Note] mysqld: ready for connections.
db_1         | Version: '10.2.27-MariaDB-1:10.2.27+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
db_1         | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_1         | 2019-10-20 17:28:42 140307860207360 [Warning] 'proxies_priv' entry '@% root@28a036cf7b3c' ignored in --skip-name-resolve mode.
db_1         | 
db_1         | 2019-10-20 17:28:42 140307857843968 [Note] mysqld (initiated by: unknown): Normal shutdown
db_1         | 2019-10-20 17:28:42 140307857843968 [Note] Event Scheduler: Purging the queue. 0 events
db_1         | 2019-10-20 17:28:42 140307269170944 [Note] InnoDB: FTS optimize thread exiting.
db_1         | 2019-10-20 17:28:42 140307857843968 [Note] InnoDB: Starting shutdown...
db_1         | 2019-10-20 17:28:42 140307152746240 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
db_1         | 2019-10-20 17:28:42 140307152746240 [Note] InnoDB: Buffer pool(s) dump completed at 191020 17:28:42
db_1         | 2019-10-20 17:28:43 140307857843968 [Note] InnoDB: Shutdown completed; log sequence number 17754885
db_1         | 2019-10-20 17:28:43 140307857843968 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1         | 2019-10-20 17:28:43 140307857843968 [Note] mysqld: Shutdown complete
db_1         | 
db_1         | 
db_1         | MySQL init process done. Ready for start up.
db_1         | 
db_1         | 2019-10-20 17:28:43 140284430554432 [Note] mysqld (mysqld 10.2.27-MariaDB-1:10.2.27+maria~bionic) starting as process 1 ...
db_1         | 2019-10-20 17:28:43 140284430554432 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1         | 2019-10-20 17:28:43 140284430554432 [Note] InnoDB: Uses event mutexes
db_1         | 2019-10-20 17:28:43 140284430554432 [Note] InnoDB: Compressed tables use zlib 1.2.11
db_1         | 2019-10-20 17:28:43 140284430554432 [Note] InnoDB: Using Linux native AIO
db_1         | 2019-10-20 17:28:43 140284430554432 [Note] InnoDB: Number of pools: 1
db_1         | 2019-10-20 17:28:43 140284430554432 [Note] InnoDB: Using SSE2 crc32 instructions
db_1         | 2019-10-20 17:28:43 140284430554432 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
db_1         | 2019-10-20 17:28:43 140284430554432 [Note] InnoDB: Completed initialization of buffer pool
db_1         | 2019-10-20 17:28:43 140283708540672 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1         | 2019-10-20 17:28:43 140284430554432 [Note] InnoDB: Highest supported file format is Barracuda.
db_1         | 2019-10-20 17:28:44 140284430554432 [Note] InnoDB: 128 out of 128 rollback segments are active.
db_1         | 2019-10-20 17:28:44 140284430554432 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1         | 2019-10-20 17:28:44 140284430554432 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1         | 2019-10-20 17:28:44 140284430554432 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1         | 2019-10-20 17:28:44 140284430554432 [Note] InnoDB: 5.7.27 started; log sequence number 17754885
db_1         | 2019-10-20 17:28:44 140283337492224 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1         | 2019-10-20 17:28:44 140283337492224 [Note] InnoDB: Buffer pool(s) load completed at 191020 17:28:44
db_1         | 2019-10-20 17:28:44 140284430554432 [Note] Plugin 'FEEDBACK' is disabled.
db_1         | 2019-10-20 17:28:44 140284430554432 [Note] Server socket created on IP: '::'.
db_1         | 2019-10-20 17:28:44 140284430554432 [Warning] 'proxies_priv' entry '@% root@28a036cf7b3c' ignored in --skip-name-resolve mode.
db_1         | 2019-10-20 17:28:44 140284430554432 [Note] Reading of all Master_info entries succeeded
cron_1       | Setting timezone to Europe/Paris...
cron_1       | Checking if librenms UID / GID has changed...
cron_1       | Setting PHP-FPM configuration...
cron_1       | Setting PHP INI configuration...
cron_1       | Setting OpCache configuration...
cron_1       | Setting Nginx configuration...
cron_1       | Updating SNMP community...
cron_1       | Initializing LibreNMS files / folders...
cron_1       | Setting LibreNMS configuration...
cron_1       | Fixing permissions...
cron_1       | Checking additional Monitoring plugins...
cron_1       | >>
cron_1       | >> Sidecar cron container detected
cron_1       | >>
cron_1       | Fixing crontab permissions...
cron_1       | 2019-10-20 17:27:38,283 INFO Included extra file "/etc/supervisord/cron.conf" during parsing
cron_1       | 2019-10-20 17:27:38,283 INFO Set uid to user 0 succeeded
cron_1       | 2019-10-20 17:27:38,305 INFO RPC interface 'supervisor' initialized
cron_1       | 2019-10-20 17:27:38,305 CRIT Server 'unix_http_server' running without any HTTP authentication checking
cron_1       | 2019-10-20 17:27:38,306 INFO supervisord started with pid 1
cron_1       | 2019-10-20 17:27:39,309 INFO spawned: 'cron' with pid 48
cron_1       | crond: crond (busybox 1.30.1) started, log level 8
cron_1       | 2019-10-20 17:27:40,327 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cron_1       | crond: USER librenms pid  49 cmd /opt/librenms/alerts.php >> /dev/null 2>&1
cron_1       | crond: USER librenms pid  54 cmd /opt/librenms/alerts.php >> /dev/null 2>&1
cron_1       | crond: USER librenms pid  59 cmd /opt/librenms/discovery.php -h new >> /dev/null 2>&1
cron_1       | crond: USER librenms pid  60 cmd /opt/librenms/alerts.php >> /dev/null 2>&1
cron_1       | crond: USER librenms pid  61 cmd /opt/librenms/poll-billing.php >> /dev/null 2>&1
cron_1       | crond: USER librenms pid  62 cmd /opt/librenms/check-services.php >> /dev/null 2>&1
cron_1       | crond: USER librenms pid  63 cmd /opt/librenms/cronic /opt/librenms/poller-wrapper.py 16
cron_1       | Cronic detected failure or error output for the command:
cron_1       | /opt/librenms/poller-wrapper.py 16
cron_1       | 
cron_1       | RESULT CODE: 1
cron_1       | 
cron_1       | ERROR OUTPUT:
cron_1       | Traceback (most recent call last):
cron_1       |   File "/opt/librenms/poller-wrapper.py", line 230, in <module>
cron_1       |     cursor.execute(query)
cron_1       |   File "/usr/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
cron_1       |     self.errorhandler(self, exc, value)
cron_1       |   File "/usr/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
cron_1       |     raise errorclass, errorvalue
cron_1       | _mysql_exceptions.ProgrammingError: (1146, "Table 'librenms.devices' doesn't exist")
cron_1       | 
cron_1       | STANDARD OUTPUT:
cron_1       | crond: USER librenms pid 100 cmd /opt/librenms/alerts.php >> /dev/null 2>&1
db_1         | 2019-10-20 17:28:44 140284430554432 [Note] Added new Master_info '' to hash table
db_1         | 2019-10-20 17:28:44 140284430554432 [Note] mysqld: ready for connections.
db_1         | Version: '10.2.27-MariaDB-1:10.2.27+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
traefik      | time="2019-10-20T15:27:34Z" level=info msg="Traefik version v1.7.18 built on 2019-09-26_01:56:30PM"
traefik      | time="2019-10-20T15:27:34Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v1.7/basics/#collected-data\n"
traefik      | time="2019-10-20T15:27:34Z" level=error msg="Failed to read new account, ACME data conversion is not available : permissions 755 for acme.json are too open, please use 600"
traefik      | time="2019-10-20T15:27:34Z" level=error msg="Unable to add ACME provider to the providers list: unable to get ACME account : permissions 755 for acme.json are too open, please use 600"
traefik      | time="2019-10-20T15:27:34Z" level=info msg="Preparing server https &{Address::443 TLS:0xc000520b40 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc0007bc1a0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
traefik      | time="2019-10-20T15:27:34Z" level=info msg="Preparing server http &{Address::80 TLS:<nil> Redirect:0xc000190b80 Auth:<nil> WhitelistSourceRange:[] WhiteList:<nil> Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc0007bc100} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
traefik      | time="2019-10-20T15:27:34Z" level=info msg="Starting server on :443"
traefik      | time="2019-10-20T15:27:34Z" level=info msg="Starting provider configuration.ProviderAggregator {}"
traefik      | time="2019-10-20T15:27:34Z" level=info msg="Starting server on :80"
traefik      | time="2019-10-20T15:27:34Z" level=info msg="Starting provider *docker.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":null,\"Trace\":false,\"TemplateVersion\":2,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"unix:///var/run/docker.sock\",\"Domain\":\"librenms.frai.se\",\"TLS\":null,\"ExposedByDefault\":false,\"UseBindPortIP\":false,\"SwarmMode\":false,\"Network\":\"\",\"SwarmModeRefreshSeconds\":15}"
traefik      | time="2019-10-20T15:27:34Z" level=info msg="Server configuration reloaded on :80"
traefik      | time="2019-10-20T15:27:34Z" level=info msg="Server configuration reloaded on :443"
traefik      | time="2019-10-20T15:27:34Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:35Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:36Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:36Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:37Z" level=info msg="Server configuration reloaded on :80"
traefik      | time="2019-10-20T15:27:37Z" level=info msg="Server configuration reloaded on :443"
traefik      | time="2019-10-20T15:27:37Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:38Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:38Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:38Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:39Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:39Z" level=info msg="Server configuration reloaded on :80"
traefik      | time="2019-10-20T15:27:39Z" level=info msg="Server configuration reloaded on :443"
traefik      | time="2019-10-20T15:27:40Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:40Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:42Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:42Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:45Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:46Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:52Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:27:53Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:28:05Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:28:06Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:28:07Z" level=warning msg="unable to find the IP address for the container \"/librenms\": the server is ignored"
traefik      | time="2019-10-20T15:28:07Z" level=error msg="undefined backend 'backend-librenms' for frontend frontend-Host-librenms-frai-se-0. Skipping frontend frontend-Host-librenms-frai-se-0..."
traefik      | time="2019-10-20T15:28:07Z" level=info msg="Server configuration reloaded on :80"
traefik      | time="2019-10-20T15:28:07Z" level=info msg="Server configuration reloaded on :443"
traefik      | time="2019-10-20T15:28:09Z" level=info msg="Server configuration reloaded on :443"
traefik      | time="2019-10-20T15:28:09Z" level=info msg="Server configuration reloaded on :80"
traefik      | time="2019-10-20T15:28:32Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:28:32Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:28:38Z" level=warning msg="unable to find the IP address for the container \"/librenms\": the server is ignored"
traefik      | time="2019-10-20T15:28:39Z" level=error msg="undefined backend 'backend-librenms' for frontend frontend-Host-librenms-frai-se-0. Skipping frontend frontend-Host-librenms-frai-se-0..."
traefik      | time="2019-10-20T15:28:39Z" level=info msg="Server configuration reloaded on :80"
traefik      | time="2019-10-20T15:28:39Z" level=info msg="Server configuration reloaded on :443"
traefik      | time="2019-10-20T15:28:41Z" level=info msg="Server configuration reloaded on :80"
traefik      | time="2019-10-20T15:28:41Z" level=info msg="Server configuration reloaded on :443"
traefik      | time="2019-10-20T15:29:23Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:29:24Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:30:24Z" level=info msg="Skipping same configuration for provider docker"
traefik      | time="2019-10-20T15:30:24Z" level=info msg="Skipping same configuration for provider docker"
smtp_1       | Setting configuration option myhostname with value: librenms.frai.se
smtp_1       | Setting configuration option mydomain with value: frai.se
smtp_1       | Setting configuration option mydestination with value: $myhostname
smtp_1       | Setting configuration option myorigin with value: $mydomain
smtp_1       | Setting configuration option relayhost with value: [smtp.gmail.com]:587
smtp_1       | Setting configuration option smtp_use_tls with value: yes
smtp_1       | Setting configuration option smtp_sasl_auth_enable with value: yes
smtp_1       | Setting configuration option smtp_sasl_password_maps with value: hash:/etc/postfix/sasl_passwd
smtp_1       | Setting configuration option smtp_sasl_security_options with value: noanonymous
smtp_1       | Adding SASL authentication configuration
smtp_1       | Setting configuration option mynetworks with value: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
smtp_1       | /usr/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
smtp_1       |   'Supervisord is running as root and it is searching '
smtp_1       | 2019-10-20 17:27:35,575 CRIT Supervisor running as root (no user in config file)
smtp_1       | 2019-10-20 17:27:35,575 WARN Included extra file "/etc/supervisord.d/rsyslog.ini" during parsing
smtp_1       | 2019-10-20 17:27:35,575 WARN Included extra file "/etc/supervisord.d/readlog.ini" during parsing
smtp_1       | 2019-10-20 17:27:35,575 WARN Included extra file "/etc/supervisord.d/postfix.ini" during parsing
smtp_1       | 2019-10-20 17:27:35,593 INFO RPC interface 'supervisor' initialized
smtp_1       | 2019-10-20 17:27:35,593 CRIT Server 'unix_http_server' running without any HTTP authentication checking
smtp_1       | 2019-10-20 17:27:35,593 INFO supervisord started with pid 23
smtp_1       | 2019-10-20 17:27:36,594 INFO spawned: 'master' with pid 26
smtp_1       | 2019-10-20 17:27:36,595 INFO spawned: 'readlog' with pid 27
smtp_1       | 2019-10-20 17:27:36,596 INFO spawned: 'rsyslog' with pid 28
smtp_1       | 2019-10-20 17:27:37,598 INFO success: master entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
smtp_1       | 2019-10-20 17:27:37,598 INFO success: readlog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
smtp_1       | 2019-10-20 17:27:37,598 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
smtp_1       | 2019-10-20 17:27:37,925 INFO exited: master (exit status 0; expected)
rrdcached_1  | Creating RRDcached configuration...
rrdcached_1  | Must specify a writable directory with -j! (Permission denied)
rrdcached_1  | Creating RRDcached configuration...
rrdcached_1  | Must specify a writable directory with -j! (Permission denied)
rrdcached_1  | Creating RRDcached configuration...
rrdcached_1  | Must specify a writable directory with -j! (Permission denied)
rrdcached_1  | Creating RRDcached configuration...
rrdcached_1  | Must specify a writable directory with -j! (Permission denied)
rrdcached_1  | Creating RRDcached configuration...
rrdcached_1  | Must specify a writable directory with -j! (Permission denied)
rrdcached_1  | Creating RRDcached configuration...
rrdcached_1  | Must specify a writable directory with -j! (Permission denied)
rrdcached_1  | Creating RRDcached configuration...
rrdcached_1  | Must specify a writable directory with -j! (Permission denied)
rrdcached_1  | Creating RRDcached configuration...
rrdcached_1  | Must specify a writable directory with -j! (Permission denied)
rrdcached_1  | Creating RRDcached configuration...
rrdcached_1  | Must specify a writable directory with -j! (Permission denied)
rrdcached_1  | Creating RRDcached configuration...
rrdcached_1  | Must specify a writable directory with -j! (Permission denied)
rrdcached_1  | Creating RRDcached configuration...
rrdcached_1  | Must specify a writable directory with -j! (Permission denied)
rrdcached_1  | Creating RRDcached configuration...
rrdcached_1  | Must specify a writable directory with -j! (Permission denied)

```

**Comment by 33Fraise33** [comment]
**.env**
```
MYSQL_DATABASE=librenms
MYSQL_USER=librenms
MYSQL_PASSWORD=passwordhere

SMTP_SERVER=smtp.gmail.com
SMTP_USERNAME=smpt@smptuser.com
SMTP_PASSWORD=

TZ=Europe/Paris
PUID=1000
PGID=1000

```
**docker-compose.yml**
```
version: "3.5"

services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=librenms.frai.se"
      - "--acme=true"
      - "--acme.acmelogging=true"
      - "--acme.email=mailhere"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.onhostrule=true"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  db:
    image: mariadb:10.2
    container_name: librenms_db
    command:
      - "mysqld"
      - "--sql-mode="
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

  memcached:
    image: memcached:alpine
    container_name: librenms_memcached
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
    restart: always

  rrdcached:
    image: crazymax/rrdcached
    container_name: librenms_rrdcached
    volumes:
      - "./librenms/rrd:/data/db"
      - "./rrd-journal:/data/journal"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "LOG_LEVEL=LOG_INFO"
      - "WRITE_TIMEOUT=1800"
      - "WRITE_JITTER=1800"
      - "WRITE_THREADS=4"
      - "FLUSH_DEAD_DATA_INTERVAL=3600"
    restart: always

  smtp:
    image: juanluisbaptiste/postfix
    container_name: librenms_smtp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:

      - "SERVER_HOSTNAME=librenms.frai.se"
      - "SMTP_SERVER=${SMTP_SERVER}"
      - "SMTP_USERNAME=${SMTP_USERNAME}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
    restart: always

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    domainname: librenms.frai.se
    hostname: librenms
    depends_on:
      - db
      - memcached
      - rrdcached
      - smtp
    volumes:
      - "./librenms:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=librenms"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:librenms.frai.se"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=30"
    env_file:
      - "./librenms.env"
    restart: always

  cron:
    image: librenms/librenms:latest
    container_name: librenms_cron
    domainname: librenms.frai.se
    hostname: librenms
    depends_on:
      - librenms
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=30"
      - "SIDECAR_CRON=1"
    env_file:
      - "./librenms.env"
    restart: always

  syslog-ng:
    image: librenms/librenms:latest
    container_name: librenms_syslog
    domainname: librenms.frai.se
    hostname: librenms
    depends_on:
      - librenms
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=30"
      - "SIDECAR_SYSLOGNG=1"
    env_file:
      - "./librenms.env"
    restart: always

```
**librenms.env**
```
MEMORY_LIMIT=1024M
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=http_x_forwarded_for

LIBRENMS_POLLER_THREADS=16
LIBRENMS_POLLER_INTERVAL=5

LIBRENMS_CRON_DISCOVERY_ENABLE=true
LIBRENMS_CRON_DAILY_ENABLE=true
LIBRENMS_CRON_ALERTS_ENABLE=true
LIBRENMS_CRON_BILLING_ENABLE=true
LIBRENMS_CRON_BILLING_CALCULATE_ENABLE=true
LIBRENMS_CRON_CHECK_SERVICES_ENABLE=true
LIBRENMS_CRON_POLLER_ENABLE=true

LIBRENMS_SNMP_COMMUNITY=librenmsdocker
MEMCACHED_HOST=memcached
MEMCACHED_PORT=11211
RRDCACHED_HOST=rrdcached
RRDCACHED_PORT=42217

```

**Comment by crazy-max** [comment]
Hi @33Fraise33, this was an issue with [rrdcached image](https://github.com/crazy-max/docker-rrdcached/blob/master/CHANGELOG.md#172-rc7-20191020). Please pull again with `docker-compose pull`.

**Comment by 33Fraise33** [comment]
these are the resulted file permissions after running with the above config: 
```
total 40
drwxr-xr-x  6 gianni gianni 4096 Oct 20 17:47 .
drwxr-xr-x 12 root   root   4096 Oct 20 16:08 ..
drwxr-xr-x  2 gianni gianni 4096 Oct 20 17:09 acme.json
drwxr-xr-x  4    999 root   4096 Oct 20 17:49 db
-rw-r--r--  1 gianni gianni 4438 Oct 20 17:05 docker-compose.yml
-rw-r--r--  1 gianni gianni  199 Oct 20 17:45 .env
drwxr-xr-x  7 root   root   4096 Oct 20 17:47 librenms
-rw-r--r--  1 gianni gianni  588 Oct 20 17:05 librenms.env
drwxr-xr-x  2 root   root   4096 Oct 20 17:47 rrd-journal

```

**Comment by crazy-max** [comment]
@33Fraise33 Can you display permissions of `librenms/`. Also, `rrd-journal` should have `1000:1000` perms.

**Comment by 33Fraise33** [comment]
> @33Fraise33 Can you display permissions of `librenms/`. Also, `rrd-journal` should have `1000:1000` perms.

I just pulled and it downloaded the latest version, still results in wrong permissions. 
```
total 40
drwxr-xr-x  6 gianni gianni 4096 Oct 20 17:52 .
drwxr-xr-x 12 root   root   4096 Oct 20 16:08 ..
drwxr-xr-x  2 gianni gianni 4096 Oct 20 17:09 acme.json
drwxr-xr-x  4    999 root   4096 Oct 20 17:52 db
-rw-r--r--  1 gianni gianni 4438 Oct 20 17:05 docker-compose.yml
-rw-r--r--  1 gianni gianni  199 Oct 20 17:45 .env
drwxr-xr-x  7 root   root   4096 Oct 20 17:52 librenms
-rw-r--r--  1 gianni gianni  588 Oct 20 17:05 librenms.env
drwxr-xr-x  2 root   root   4096 Oct 20 17:52 rrd-journal
```
```
total 28
drwxr-xr-x 7 root   root   4096 Oct 20 17:52 .
drwxr-xr-x 6 gianni gianni 4096 Oct 20 17:52 ..
drwxr-xr-x 2 gianni gianni 4096 Oct 20 17:52 config
drwxrwxr-x 2 gianni gianni 4096 Oct 20 17:52 logs
drwxr-xr-x 2 gianni gianni 4096 Oct 20 17:52 monitoring-plugins
drwxrwxr-x 2 gianni gianni 4096 Oct 20 17:52 rrd
drwxr-xr-x 2 gianni gianni 4096 Oct 20 17:52 syslog-ng
```

**Comment by crazy-max** [comment]
`rrd-journal` perms must be fixed with `1000:1000` on your own: `chown -R 1000:1000 rrd-journal`.

**Comment by 33Fraise33** [comment]
> `rrd-journal` perms must be fixed with `1000:1000` on your own: `chown -R 1000:1000 rrd-journal`.

That fixed it, thanks for that, before the pull this was not working but now it is.

**Comment by crazy-max** [comment]
Ok nice, I will add a note about rrdcached issue, thanks for your input!

**Comment by 33Fraise33** [comment]
@crazy-max I'm still unable to get mariadb to run as my user instead of 999, is that a known issue or something I can fix? I want to automate my deployment with ansible, but my owner is constantly changed from the generated 999 user back to mine when I run my script.

**Comment by crazy-max** [comment]
@33Fraise33 If this concerns mariadb volume permissions you should post an issue on [docker-library/mariadb](https://github.com/docker-library/mariadb) repo about this.

**Comment by TreeSloths** [comment]
> Ok nice, I will add a note about rrdcached issue, thanks for your input!

Hi. This is still an issue.
